language: groovy

jdk:
    - oraclejdk7

env:
    - GRAILS_VERSION=2.3.5

before_install:
    - mkdir -p ~/.m2
    - bash -c '{ curl http://files.thehyve.net/caches/grails_${GRAILS_VERSION}_mvncache.tar.gz  | tar -C ~/.m2 -xzf -; } || true'

install:
    - mkdir -p ~/.grails
    - cd ~/.grails
    - curl -O http://dist.springframework.org.s3.amazonaws.com/release/GRAILS/grails-${GRAILS_VERSION}.zip
    - unzip grails-${GRAILS_VERSION}.zip
    - export GRAILS_HOME=~/.grails/grails-${GRAILS_VERSION}
    - cd -

script:
    - ${GRAILS_HOME}/bin/grails refresh-dependencies --non-interactive
    - ${GRAILS_HOME}/bin/grails upgrade --non-interactive
    - ${GRAILS_HOME}/bin/grails test-app --non-interactive --stacktrace

